name: Continuous deployment

on:
  workflow_run:
    workflows: ["Continuous integration"]
    branches: [master]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Build
      run: make build

    - name: ZIP build
      run:  zip ${{ github.run_id }}.zip bootstrap

    - name: Upload to S3
      run: aws s3 cp ${{ github.run_id }}.zip s3://coucou33-api-bucket/${{ github.run_id }}.zip

    - name: Update lambda function code
      run: aws lambda update-function-code --function-name coucou33-api --s3-bucket coucou33-api-bucket --s3-key ${{ github.run_id }}.zip

    - name: Release new lambda function version
      run: aws lambda publish-version --function-name coucou33-api
    